services:
  server:
    image: tavov21/store_backend:latest
    container_name: nodeapp
    ports:
      - 5000:5000
    environment:
      NODE_ENV: production
    command: bash -c "sleep 10 && yarn start"
    networks:
      - mi_red

  client:
    image: tavov21/store_frontend:latest
    container_name: reactapp
    depends_on:
      - server
    ports:
      - 3000:80
    networks:
      - mi_red

networks:
  mi_red:
    driver: bridge
